=== pabvald/chatbot/docs/schemas/intent.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",
    "required": [
        "name",
        "training_phrases",
        "action",
        "parameters",
        "responses"     
    ],
    "properties": {
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "description": "An explanation about the purpose of this instance."
        },
        "training_phrases": {
            "$id": "#/properties/training_phrases",
            "type": "object",
            "title": "The Training_phrases Schema",
            "description": "An explanation about the purpose of this instance.",
            "required": [
                "en",
                "es"
            ],
            "properties": {
                "en": {
                    "$id": "#/properties/training_phrases/properties/en",
                    "type": "array",
                    "title": "The En Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "items": {
                        "$id": "#/properties/training_phrases/properties/en/items",
                        "type": "string",
                        "title": "The Items Schema",
                        "description": "An explanation about the purpose of this instance."
                    }
                },
                "es": {
                    "$id": "#/properties/training_phrases/properties/es",
                    "type": "array",
                    "title": "The Es Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "items": {
                        "$id": "#/properties/training_phrases/properties/es/items",
                        "type": "string",
                        "title": "The Items Schema",
                        "description": "An explanation about the purpose of this instance."
                    }
                }
            }
        },
        "action": {
            "$id": "#/properties/action",
            "type": "string",
            "title": "The Action Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": ""
        },
        "parameters": {
            "$id": "#/properties/parameters",
            "type": "array",
            "title": "The Parameters Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "items": {
                "$id": "#/properties/parameters/items",
                "type": "object",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",               
                "required": [
                    "name",
                    "required",
                    "prompts",
                    "entity"
                ],
                "properties": {
                    "name": {
                        "$id": "#/properties/parameters/items/properties/name",
                        "type": "string",
                        "title": "The Name Schema",
                        "description": "An explanation about the purpose of this instance."            
                    },
                    "required": {
                        "$id": "#/properties/parameters/items/properties/required",
                        "type": "boolean",
                        "title": "The Required Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": false                        
                    },
                    "prompts": {
                        "$id": "#/properties/parameters/items/properties/prompts",
                        "type": "object",
                        "title": "The Prompts Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "required": [
                            "en",
                            "es"
                        ],
                        "properties": {
                            "en": {
                                "$id": "#/properties/parameters/items/properties/prompts/properties/en",
                                "type": "array",
                                "title": "The En Schema",
                                "description": "An explanation about the purpose of this instance.",
                                "items": {
                                    "$id": "#/properties/parameters/items/properties/prompts/properties/en/items",
                                    "type": "string",
                                    "title": "The Items Schema",
                                    "description": "An explanation about the purpose of this instance."                                
                                }
                            },
                            "es": {
                                "$id": "#/properties/parameters/items/properties/prompts/properties/es",
                                "type": "array",
                                "title": "The Es Schema",
                                "description": "An explanation about the purpose of this instance.",
                                "items": {
                                    "$id": "#/properties/parameters/items/properties/prompts/properties/es/items",
                                    "type": "string",
                                    "title": "The Items Schema",
                                    "description": "An explanation about the purpose of this instance."
                                }
                            }
                        }
                    },
                    "entity": {
                        "$id": "#/properties/parameters/items/properties/entity",
                        "type": "string",
                        "title": "The Entity Schema",
                        "description": "An explanation about the purpose of this instance."
                    }
                }
            }
        },
        "responses": {
            "$id": "#/properties/responses",
            "type": "object",
            "title": "The Responses Schema",
            "description": "An explanation about the purpose of this instance.",
            "required": [
                "en",
                "es"
            ],
            "properties": {
                "en": {
                    "$id": "#/properties/responses/properties/en",
                    "type": "array",
                    "title": "The En Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "items": {
                        "$id": "#/properties/responses/properties/en/items",
                        "type": "string",
                        "title": "The Items Schema",
                        "description": "An explanation about the purpose of this instance."  
                    }
                },
                "es": {
                    "$id": "#/properties/responses/properties/es",
                    "type": "array",
                    "title": "The Es Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "items": {
                        "$id": "#/properties/responses/properties/es/items",
                        "type": "string",
                        "title": "The Items Schema",
                        "description": "An explanation about the purpose of this instance."                        
                    }
                }
            }
        }         
    }
}

=== pabvald/chatbot/intents/definitions/farewell.json
{
    "name": "farewell",    
    "training_phrases": {
        "en": [
            "good bye",
            "bye bye",
            "see you later",
            "see ya",
            "see you",
            "bye",
            "goodbye",
            "see you soon"
        ],
        "es":[
            "adiós",
            "hasta luego",
            "me voy",
            "nos vemos",
            "hasta pronto",
            "nos vemos pronto",
            "me piro",
            "chao",
            "adiós adiós"
        ] 
    }, 
    "action": "",
    "parameters": [],
    "responses":{
        "en": [
            "Good bye!",
            "See your later!",
            "See you soon!",
            "Bye, bye!",
            "Bye, human!"
        ],
        "es":[
            "¡Hasta luego!",
            "¡Nos vemos pronto!",
            "Adiós, adiós",
            "Adiós, humano"
        ]  
    }    
}

=== pabvald/chatbot/intents/definitions/fallback.json
{
    "name": "fallback",
    "training_phrases":{
        "en": [
            "damn",
            "how old are you?",
            "i love you",
            "what is the minimum number of credits i need to course ?",
            "i still don't have my student card and i need it, what should i do?",
            "can i take an exam if i am in my home country?",
            "whats's the weather like?",
            "you are so annoying",
            "can i study in english at the uva?",
            "i love you",
            "say something"
        ],

        "es":[
            "puedes contarme un chiste?",
            "cuántos años tienes?",
            "dime algo gracioso",
            "cuál es el mínimo número de créditos que puedo estudiar?",
            "eres molesto",
            "¿cómo hace hoy?",
            "te quiero",
            "di algo",
            "las setas te aportan nutrientes",
            "quiero pedir una pizza, por favor",
            "qué asignaturas puedo estudiar en la universidad de valladolid?",
            "en qué idiomas son las clases de la UVA?",
            "cuando son los exámenes extraordinarios?",
            "mierda"
        ] 
    },
    "action": "",
    "parameters": [],
    "responses": {
        "en":[
            "I didn't get that. Can you say it again?",
            "I missed what you said. What was that?",
            "Sorry, could you say that again",
            "Can you say that again?",
            "Sorry, i didn't get that. Can you rephrase?",
            "Sorry, what was that?",
            "One more time?",
            "What was that?",
            "Say that on more time?",
            "I didn't get that. Can you repeat?",
            "I missed that, say that again?"
        ],
        "es":[
            "Ups, no he entendido a qué te refieres",
            "¿Podrías repetirlo, por favor?",
            "¿Disculpa?",
            "¿Decías?",
            "¿Cómo?",
            "Lo siento, pero no te he entendido bien. ¿Puedes repetirlo?",
            "Lo siento, ¿puedes decirlo de nuevo?"
        ]  
    }    
}

=== pabvald/chatbot/intents/definitions/thank.json
{
    "name": "thank",
    "training_phrases":{
        "en":[
            "thanks",
            "thank you!",
            "appreciate that",
            "appreciate it",
            "thanks a lot",
            "ty",
            "thank you very much",
            "thanks, you are the best"
        ],
        "es":[
            "grax",
            "gracias",
            "muchas gracias!",
            "te lo agradezco",
            "gracias, eres el mejor",
            "much√≠simas gracias!"
        ] 
    },
    "action": "",
    "parameters": [],
    "responses":{
        "en": [
            "You're welcome",
            "I do my best",
            "It was nothing :)"
        ],
        "es":[
            "De nada",
            "Hago lo que puedo",
            "No ha sido nada :)"
        ] 
    }
}

=== pabvald/chatbot/intents/definitions/contact.json
{
    "name": "contact",
    "training_phrases":{
        "en": [      
            "office hours",
            "office address",
            "office telephone",
            "office email",
            "office contact",
            "office schedule",
            "contact information",
            "do you have some contact info?",
            "what are the office hours?",
            "can you give me the contact information?",
            "what is the address of the international relationships office?",
            "where is the office?",
            "when is the office opened?"
        ],
        "es": [
            "horario de la oficina",
            "dirección de la oficina",
            "teléfono de la oficina",
            "contacto de la oficina",
            "email de la oficina",
            "información de contacto",
            "cuál es el horario de la oficina?",
            "¿puedes darme la información de contacto?",
            "dime el número de la oficina",
            "dónde está la oficina de relaciones internacionales?",
            "¿cómo puedo contactar con la oficina?",
            "¿tienes información de contacto?"
        ] 
    },  
    "action": ""  ,
    "parameters": [],
    "responses":{
        "en": [
            "Here's the information about the International Relationships office:\n\n<b>Address</b>\n\t\tCasa del Estudiante (Ground floor)\n\t\tC/ Real de Burgos s/n\n\t\t47011 Valladolid (España)\n\t\t<a href=\"https://goo.gl/maps/H3TAdURuHusdwugB9\">(See it in Google Maps)</a>\n<b>Hours</b>\n\t\tMon. to Fri., 09:00 - 14:00h\n<b>Telephone</b>\n\t\t+34 983 42 32 83\n<b>Email</b>\n\t\trelint@uva.es\n"
        ],
        "es":[
            "Aquí tienes la información sobre la oficina de Relaciones Internacionales:\n\n<b>Dirección</b>\n\t\tCasa del Estudiante (Planta Baja)\n\t\tC/ Real de Burgos s/n\n\t\t47011 Valladolid (España)\n\t\t<a href=\"https://goo.gl/maps/H3TAdURuHusdwugB9\">(Ver en Google Maps)</a>\n<b>Horario</b>\n\t\tLun. a Vie., 09:00 - 14:00h\n<b>Teléfono</b>\n\t\t+34 983 42 32 83\n<b>Email</b>\n\t\trelint@uva.es"
        ] 
    }
}

=== pabvald/chatbot/intents/definitions/welcome.json
{
    "name": "welcome",
    "training_phrases":{
        "en": [
            "hello",
            "hi",
            "greetings, bot",
            "just going to say hi",
            "heya",
            "howdy",
            "hey there",
            "hi there",
            "hey",
            "greetings",
            "hello again",
            "hello there",
            "lovely day isn't it"
        ],
        "es":[
            "hace un día precioso, no crees?",
            "hola de nuevo",
            "cuánto tiempo!",
            "buenos días",
            "hola, qué tal?",
            "saludos",
            "buenas",
            "hola"
        ] 
    },
    "action": "",
    "parameters": [],
    "responses":{        
        "en" :  [ 
            "Hi.\nI'm Relint Bot. I'm here to help you solve any question about studying at the University of Valladolid. If you have any doubts, you ask me for help."
        ],
        "es":[
            "Hola.\nMi nombre es Relint Bot. Estoy aquí para resolver cualquier duda que tengas sobre tu estancia en la Universidad de Valladolid. Si tienes alguna duda, puedes pedirme ayuda."
        ] 
    }   
}

=== pabvald/chatbot/intents/definitions/cancel.json
{
    "name": "cancel",
    "training_phrases":{
        "en":[
            "i want to cancel",
            "abort",
            "exit",
            "cancel it",
            "cancel",
            "go back",
            "I want to cancel the appointment",
            "cancel the appointment"
         ],
        "es":[
            "cancelar",
            "quiero cancelarlo",
            "salir",
            "cancelalo",
            "abortar",
            "atr√°s",
            "quiero cancelar la cita",
            "cancelar la cita"
        ]  
    },
    "action": "deactivate_intent",
    "parameters": [],   
    "responses":{
        "en": [
            "Okay, we'll leave it for another time.",
            "Of course. We can leave it for another time."
        ],
        "es":[
            "De acuerdo, lo dejamos para otro momento.",
            "Por supuesto. Podemos dejarlo para otro momento."
        ] 
    }    
}

=== pabvald/chatbot/intents/definitions/help.json
{
    "name": "help",
    "training_phrases":{
        "en": [
            "can you give me a hand here?",
            "i don't know what to do",
            "any help?",
            "can you help me?",
            "help me",
            "help",
            "what can you do?",
            "how do you work?",
            "i need help"
        ],
        "es": [
            "qué eres capaz de hacer?",
            "qué puedes hacer?",
            "necesito ayuda",
            "ayuda",
            "puedes ayudarme?",
            "¿alguna ayuda?",
            "ayúdame",
            "necesito tu ayuda",
            "¿puedes echarme una mano?"
        ] 
    },  
    "action": ""  ,
    "parameters": [],
    "responses":{
        "en": [
            "I am able to\n\n<b>+</b> Answer FAQs about studying at the UVa\n<b>+</b> Make an appointment in the International Relationships office so that you can talk to a person."
        ],
        "es":[
            "Si no soy capaz de resolverte una pregunta, puedo <b>concertar una cita</b> para que puedas hablar con una persona en la oficina de Relaciones Internacionales."
        ] 
    }
}

=== pabvald/chatbot/intents/definitions/appointment.json
{
    "name": "appointment",
    "training_phrases":{
        "en": [
            "make an appointment",
            "i want to make an appointment",
            "can i make an appointment ?",
            "i would like to make an appointment",
            "make appointment",
            "i want to make an appointment for next monday at 12:00 am",
            "i would like to make an appointment to discuss erasmus studies",
            "make appointment for 04/12/2020 at 21:34 to talk about language courses",
            "appointment for tomorrow at 2 pm",
            "appointment fot the 3rd of April at 8:45",
            "make appointment for tomorrow"
         ],
        "es": [
            "concertar cita",
            "quiero concertar una cita",
            "¿puedo concertar una cita?",
            "me gustaría concertar una cita",
            "concertar una cita",
            "quiero concertar una cita para el próximo lunes a las 12:15",
            "me gustaría concertar uan cita para hablar sobre estudios erasmus",
            "concertar cita para el 04/12/2020 a las 11 am para hablar de cursos de idiomas",
            "cita par mañana a las 9 p.m",
            "cita para el 3 de abril a las 8:45",
            "concertar cita para mañana"
        ]  
    }, 
    "action": "make_appointment",
    "parameters": [
        {
            "name": "topic",
            "required": true,
            "prompts":{
                "en":[
                    "What matter do you want to discuss in your appointment?",
                    "Please, indicate the matter to be discussed in the appointment."
                ],
                "es":[
                    "Por favor, indica el asunto a tratar.",
                    "¿Qué tema te gustaría tratar en la cita?"
                ] 
            },                
            "entity": "TOPIC"
        },
        {
            "name": "date",
            "required": true,
            "prompts":{ 
                "en":[
                    "What date would you like to have the appointment?",
                    "Please, indicate the desired date of the appointment."
                ],
                "es":[
                    "¿Qué día te gustaría tener la cita?",
                    "Por favor, indicar el día deseado para la cita."
                ] 
            },             
            "entity": "DATE"
        },
        {
            "name": "time",
            "required": true,
            "prompts": { 
                "en":[
                    "What time would you like to have the appointment?",
                    "Please, indicate the desired time for the appointment."
                ],
                "es":[
                    "¿A qué hora te gustaría tener tu cita?",
                    "Por favor, indica la hora a la que deseas tener la cita."
                ] 
            },  
            "entity": "TIME"
        }        
    ],
    "responses":{
        "en": [
            "An appointment has been made for {date} at {time}, to discuss {topic}."
        ],
        "es":[
            "Se ha concertado una cita para el {date} a las {time}, para hablar sobre {topic}."
        ]     
    }
}
